print("How old are you", end = " ")
age = input()
print("How tall are you?", end = " ")
height = input()
print("How much do you weigh?", end = "")
weight = int(input())
print(f'So,  you are age is {age}, height is {height} tall and weight is {weight} and you are fit')
print(type(age))
print(type(height))
print(type(weight))