from sys import argv
script, filename = argv
print(f"We are going to erase {filename}")
print("If you dont want that hit ctrl + c else press return/enter")
input('?')
print("openening file")
target = open(filename, 'w')
print("Truncating the file....")
target.truncate()
print("now i am going to ask you for a few lines to enter in the file")
line1 = input("line1: ")
line2 = input("line2: ")
line3 = input("line4: ")
target.write(line1)
target.write('\n')
target.write(line2)
target.write('\n')
target.write(line3)
print('and finally we save the file')
target.close()
